[package]
authors = ["29rou <g196010r@icu.ac.jp>"]
name = "c-som"
version = "0.1.0"

[dependencies]
num = "0.1.42"
typenum = "1.10.0"
itertools = "0.7.8"
generic-array = "0.11.0"
rand = "0.4.2"

[dependencies.num-traits]
version = "0.2.2"
default-features = false
